# TCL File Generated by Component Editor 15.0
# Sat Nov 25 21:56:00 CST 2017
# DO NOT MODIFY


# 
# chess_game_core "Chess Game Core" v1.0
# Griffin A. Tucker 2017.11.25.21:56:00
# This module stores chess game memory
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module chess_game_core
# 
set_module_property DESCRIPTION "This module stores chess game memory"
set_module_property NAME chess_game_core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ECE 385 Custom IPs"
set_module_property AUTHOR "Griffin A. Tucker"
set_module_property DISPLAY_NAME "Chess Game Core"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file chess_game_interface.sv SYSTEM_VERILOG PATH chess_game_interface.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file chess_game_interface.sv SYSTEM_VERILOG PATH chess_game_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point Chess_Slave
# 
add_interface Chess_Slave avalon end
set_interface_property Chess_Slave addressUnits WORDS
set_interface_property Chess_Slave associatedClock CLK
set_interface_property Chess_Slave associatedReset RESET
set_interface_property Chess_Slave bitsPerSymbol 8
set_interface_property Chess_Slave burstOnBurstBoundariesOnly false
set_interface_property Chess_Slave burstcountUnits WORDS
set_interface_property Chess_Slave explicitAddressSpan 0
set_interface_property Chess_Slave holdTime 0
set_interface_property Chess_Slave linewrapBursts false
set_interface_property Chess_Slave maximumPendingReadTransactions 0
set_interface_property Chess_Slave maximumPendingWriteTransactions 0
set_interface_property Chess_Slave readLatency 0
set_interface_property Chess_Slave readWaitStates 0
set_interface_property Chess_Slave readWaitTime 0
set_interface_property Chess_Slave setupTime 0
set_interface_property Chess_Slave timingUnits Cycles
set_interface_property Chess_Slave writeWaitTime 0
set_interface_property Chess_Slave ENABLED true
set_interface_property Chess_Slave EXPORT_OF ""
set_interface_property Chess_Slave PORT_NAME_MAP ""
set_interface_property Chess_Slave CMSIS_SVD_VARIABLES ""
set_interface_property Chess_Slave SVD_ADDRESS_GROUP ""

add_interface_port Chess_Slave ADDR address Input 8
add_interface_port Chess_Slave READ read Input 1
add_interface_port Chess_Slave WRITE write Input 1
add_interface_port Chess_Slave CS chipselect Input 1
add_interface_port Chess_Slave BYTE_EN byteenable Input 4
add_interface_port Chess_Slave WRITE_DATA writedata Input 32
add_interface_port Chess_Slave READ_DATA readdata Output 32
set_interface_assignment Chess_Slave embeddedsw.configuration.isFlash 0
set_interface_assignment Chess_Slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment Chess_Slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment Chess_Slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point EXPORT_DATA
# 
add_interface EXPORT_DATA conduit end
set_interface_property EXPORT_DATA associatedClock CLK
set_interface_property EXPORT_DATA associatedReset ""
set_interface_property EXPORT_DATA ENABLED true
set_interface_property EXPORT_DATA EXPORT_OF ""
set_interface_property EXPORT_DATA PORT_NAME_MAP ""
set_interface_property EXPORT_DATA CMSIS_SVD_VARIABLES ""
set_interface_property EXPORT_DATA SVD_ADDRESS_GROUP ""

add_interface_port EXPORT_DATA EXPORT_DATA EXPORT_DATA Output 32

